package com.sunline.qi.tag;

import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;

/**
 * Created by sunline on 2016/9/18.
 */
public class DCInfoTag {
    public TextView route1;
    public EditText name1;
    public Spinner attr1;
    public Spinner symbol1;
    public EditText per1;
    public TextView route2;
    public EditText name2;
    public Spinner attr2;
    public Spinner symbol2;
    public EditText per2;
    public TextView route3;
    public EditText name3;
    public Spinner attr3;
    public Spinner symbol3;
    public EditText per3;
    public TextView route4;
    public EditText name4;
    public Spinner attr4;
    public Spinner symbol4;
    public EditText per4;
    public TextView route5;
    public EditText name5;
    public Spinner attr5;
    public Spinner symbol5;
    public EditText per5;
    public TextView route6;
    public EditText name6;
    public Spinner attr6;
    public Spinner symbol6;
    public EditText per6;
    public TextView route7;
    public EditText name7;
    public Spinner attr7;
    public Spinner symbol7;
    public EditText per7;
    public TextView route8;
    public EditText name8;
    public Spinner attr8;
    public Spinner symbol8;
    public EditText per8;
    public TextView route9;
    public EditText name9;
    public Spinner attr9;
    public Spinner symbol9;
    public EditText per9;
    public TextView route10;
    public EditText name10;
    public Spinner attr10;
    public Spinner symbol10;
    public EditText per10;
    public TextView route11;
    public EditText name11;
    public Spinner attr11;
    public Spinner symbol11;
    public EditText per11;
    public TextView route12;
    public EditText name12;
    public Spinner attr12;
    public Spinner symbol12;
    public EditText per12;
    public TextView route13;
    public EditText name13;
    public Spinner attr13;
    public Spinner symbol13;
    public EditText per13;
    public TextView route14;
    public EditText name14;
    public Spinner attr14;
    public Spinner symbol14;
    public EditText per14;
    public TextView route15;
    public EditText name15;
    public Spinner attr15;
    public Spinner symbol15;
    public EditText per15;
    public TextView route16;
    public EditText name16;
    public Spinner attr16;
    public Spinner symbol16;
    public EditText per16;
}
